package com.smarthane.android.atlas.app.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smarthane.android.atlas.mvp.model.entity.DaoGankEntity;

import com.smarthane.android.atlas.app.greendao.DaoGankEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoGankEntityDaoConfig;

    private final DaoGankEntityDao daoGankEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoGankEntityDaoConfig = daoConfigMap.get(DaoGankEntityDao.class).clone();
        daoGankEntityDaoConfig.initIdentityScope(type);

        daoGankEntityDao = new DaoGankEntityDao(daoGankEntityDaoConfig, this);

        registerDao(DaoGankEntity.class, daoGankEntityDao);
    }
    
    public void clear() {
        daoGankEntityDaoConfig.clearIdentityScope();
    }

    public DaoGankEntityDao getDaoGankEntityDao() {
        return daoGankEntityDao;
    }

}
